-- Testimony: a Lean 4 library for machine-checkable models of biblical
-- arguments. See the documentation site, or docs/src/ in this repository.
import Testimony.Text
import Testimony.Attr
import Testimony.Bib.Core
import Testimony.Bib.Attr
import Testimony.Bib.Works
import Testimony.Bib.Registry
import Testimony.Bib.Render
import Testimony.Provenance
import Testimony.Intertext
import Testimony.Scripture
import Testimony.Logic.Basic
import Testimony.Logic.Notation
import Testimony.Logic.Entail
import Testimony.Logic.Package
import Testimony.Logic.Line
import Testimony.Logic.Tactic
import Testimony.Logic.Framework
import Testimony.Logic.Dispute
import Testimony.Logic.Horn
import Testimony.Logic.Solver
import Testimony.Logic.Witness
import Testimony.Logic.Because
import Testimony.Logic.Verdict
import Testimony.Logic.Support
import Testimony.Logic.Map
import Testimony.Argument
import Testimony.Arguments.BornInBethlehem
import Testimony.Arguments.BornOfAVirgin
import Testimony.Arguments.SolaFide
import Testimony.Arguments.SolaScriptura
import Testimony.Checks.Refutations
