import Testimony.Tools.Pages

/-!
# argdoc — publish each argument as a page of the documentation site

`lake exe argdoc` writes `docs/src/arguments/<slug>.md` for every argument in
`Testimony.Doc.arguments`, and splices the list of them into the marked block
of `docs/src/SUMMARY.md`. The pages themselves are harvested and rendered by
`Testimony.Tools.Pages`; what lives here is the shell around them — the page's
title and standing note, the file layout, and the `--check` that fails CI when
a committed page is not what the source now says.

```sh
lake exe argdoc            # rewrite docs/src/arguments/ and the SUMMARY block
lake exe argdoc --check    # verify the committed pages match the source
```
-/

open Lean Testimony Testimony.Doc

namespace Testimony.Doc


/-- The note every generated page opens with, under its title.

It says three things a reader meets in the first screen and would otherwise
have to infer: that the prose is the source's own, what the numbering is, and
what the two marks mean. -/
def preamble (a : Argument) : String :=
  "*This page is generated from [`" ++ sourcePath a.ns ++ "`](https://github.com/" ++
  "testimonyproject/testimony/blob/main/" ++ sourcePath a.ns ++ "). Every heading and " ++
  "paragraph below is a docstring in those files; every formula is rendered from the " ++
  "encoding they check. If the page and the source disagree, the page is the one that " ++
  "is wrong, and regenerating it is the fix.*\n\n" ++
  "Atoms are numbered propositional variables, numbered once for the whole page, so " ++
  "the same variable means the same claim in every position below. " ++
  "[Reading the logic](../reading-the-logic.md) is the short version of what the " ++
  "notation means. A result marked ⚗ is one this library constructs rather than " ++
  "reports.\n\n"

/-- One argument's page: the do-not-edit header, the title, the note, the
generated body. -/
def page (a : Argument) : Option String :=
  (bodyOf a.ns).map fun b =>
    "<!-- Generated by `lake exe argdoc`. Do not edit by hand. -->\n" ++
    "<!-- Source of truth: " ++ sourcePath a.ns ++ " -->\n\n" ++
    "# " ++ a.title ++ "\n\n" ++ preamble a ++ b.markdown

/-- Every generated page, as a file name under `docs/src/arguments/` and its
contents. -/
def pages : List (String × String) :=
  arguments.filterMap fun a => (page a).map fun p => (a.slug ++ ".md", p)

/-- The block `argdoc` owns in `docs/src/SUMMARY.md`. -/
def summaryMarkdown : String :=
  String.join (arguments.map fun a =>
    "- [" ++ a.title ++ "](./arguments/" ++ a.slug ++ ".md)\n")

end Testimony.Doc

open Testimony.Doc

/-- Where the generated pages are written. -/
def pagesDir : System.FilePath := "docs/src/arguments"

/-- The page carrying the generated list of arguments. -/
def summaryPath : System.FilePath := "docs/src/SUMMARY.md"

/-- Opening marker of the block `argdoc` owns in `SUMMARY.md`. -/
def beginMarker : String := "<!-- BEGIN GENERATED: lake exe argdoc -->"

/-- Closing marker. -/
def endMarker : String := "<!-- END GENERATED: lake exe argdoc -->"

/-- Read a file, treating absence as empty so `--check` reports it as stale
rather than failing. -/
def readOrEmpty (p : System.FilePath) : IO String := do
  if ← p.pathExists then IO.FS.readFile p else pure ""

/-- Pages present in `docs/src/arguments/` that `argdoc` does not generate.

An argument that is renamed or removed leaves its old page behind, and a stale
page asserting a result the library no longer has is the failure this project
exists to rule out. Reported rather than deleted: the tool says what to remove,
and a human removes it. -/
def strayPages : IO (Array System.FilePath) := do
  unless ← pagesDir.pathExists do return #[]
  let wanted := pages.map (·.1)
  let mut stray := #[]
  for entry in ← pagesDir.readDir do
    let name := entry.fileName
    if name.endsWith ".md" && !wanted.contains name then
      stray := stray.push entry.path
  return stray.qsort (·.toString < ·.toString)

/-- Entry point. -/
def main (args : List String) : IO UInt32 := do
  unless ← summaryPath.pathExists do
    IO.eprintln s!"argdoc: {summaryPath} does not exist"
    return 1
  let summary ← IO.FS.readFile summaryPath
  let body := summaryMarkdown ++ "\n"
  let updated ← match Testimony.Logic.Markdown.splice beginMarker endMarker summary body with
    | .error e => do IO.eprintln s!"argdoc: {summaryPath}: {e}"; return 1
    | .ok s => pure s
  let stray ← strayPages
  if args.contains "--check" then
    let mut ok := true
    for (name, text) in pages do
      if (← readOrEmpty (pagesDir / name)) != text then
        IO.eprintln s!"argdoc: docs/src/arguments/{name} is stale"
        ok := false
    if summary != updated then
      IO.eprintln s!"argdoc: the generated block in {summaryPath} is stale"
      ok := false
    for p in stray do
      IO.eprintln s!"argdoc: {p} is not generated by argdoc — delete it"
      ok := false
    if ok then
      IO.println s!"argdoc: {pages.length} argument pages are up to date"
      return 0
    IO.eprintln "argdoc: run `lake exe argdoc` and commit the result"
    return 1
  IO.FS.createDirAll pagesDir
  for (name, text) in pages do
    IO.FS.writeFile (pagesDir / name) text
  IO.FS.writeFile summaryPath updated
  for p in stray do
    IO.eprintln s!"argdoc: warning: {p} is not generated by argdoc — delete it"
  IO.println s!"argdoc: wrote {pages.length} pages to {pagesDir} and updated {summaryPath}"
  return 0
